### ISSUE TITLE
Adicionar animação de fundo

### ISSUE THREAD

**Issue by NahiGit** [Bielxasa/Bielxasa#1]
Uma sugestão de melhoria para o projeto, visualmente falando.

Seria bacana adicionar uma imagem de corte de cabelo que funcione como um fundo animado, ao invés daquela foto estática, acho que agradaria mais o visual da página.

**Comment by Bielxasa** [comment]
Olá NahiGit obrigado por sua contribuição. Irei fazer essa atualização. Obrigado pela sugestão.
